-- +goose Up
-- +goose StatementBegin
CREATE FUNCTION reject_mutation() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'table % is insert-only', TG_TABLE_NAME;
END;
$$ LANGUAGE plpgsql;
-- +goose StatementEnd

-- symbols: version key isin. symbol_id is stable per ISIN across ticker renames;
-- the first row for an ISIN generates it, later versions reuse it explicitly.
CREATE TABLE symbols (
    symbol_id   bigint GENERATED BY DEFAULT AS IDENTITY,
    isin        text        NOT NULL,
    ticker      text        NOT NULL,
    ingested_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (symbol_id, ingested_at),
    UNIQUE (isin, ingested_at)
);
CREATE INDEX symbols_isin_idx ON symbols (isin, ingested_at DESC);
CREATE TRIGGER symbols_insert_only BEFORE UPDATE OR DELETE ON symbols
    FOR EACH ROW EXECUTE FUNCTION reject_mutation();

-- bars: stored exactly as the source reports them (eod2 = adjusted in place,
-- nse-bhavcopy = unadjusted). Version key (symbol_id, date, source).
CREATE TABLE bars (
    symbol_id    bigint         NOT NULL,
    date         date           NOT NULL,
    source       text           NOT NULL,
    series       text           NOT NULL,
    open         numeric(14,4)  NOT NULL,
    high         numeric(14,4)  NOT NULL,
    low          numeric(14,4)  NOT NULL,
    close        numeric(14,4)  NOT NULL,
    volume       bigint         NOT NULL,
    turnover     numeric(20,2),
    delivery_qty bigint,
    content_hash bytea          NOT NULL,
    ingested_at  timestamptz    NOT NULL DEFAULT now(),
    PRIMARY KEY (symbol_id, date, source, ingested_at)
);
CREATE INDEX bars_source_date_idx ON bars (source, date);
CREATE TRIGGER bars_insert_only BEFORE UPDATE OR DELETE ON bars
    FOR EACH ROW EXECUTE FUNCTION reject_mutation();

-- ingest_log: one row per fetch attempt; drives resumable backfills.
CREATE TABLE ingest_log (
    source     text        NOT NULL,
    date       date        NOT NULL,
    status     text        NOT NULL CHECK (status IN ('ok', 'no-file', 'error')),
    rows       integer     NOT NULL DEFAULT 0,
    note       text,
    fetched_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (source, date, fetched_at)
);

-- bars_latest: the current version of every bar (all sources).
CREATE VIEW bars_latest AS
    SELECT DISTINCT ON (symbol_id, date, source) *
    FROM bars
    ORDER BY symbol_id, date, source, ingested_at DESC;

-- +goose Down
DROP VIEW bars_latest;
DROP TABLE ingest_log;
DROP TABLE bars;
DROP TABLE symbols;
DROP FUNCTION reject_mutation();
